name: Fetch latest Irish COVID data at 1am

#on: [workflow_dispatch] #repository_dispatch: #Can run it manually also
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "scheduled-fetch-data"
  scheduled-fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: checkoout the code
      uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: configure pip caching
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python_requirements.txt
    - name: Fetch, update and commit COVID-Ireland data
      run: . /DATA/get-data.sh