#on: [push, pull_request]
on: [workflow_dispatch]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: install-packages
        run: |
         Rscript -e "install.packages(c('rsconnect'), type  = 'binary')"
      - name: authorise-shiny
        run: |
         Rscript -e "rsconnect::setAccountInfo(name='iboboburo', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
         Rscript -e "rsconnect::deployApp(appName = 'coviddash')"
