on:
  # manual deploy
  # trigger the workflow on pull request on master branch 
  # schedule to run at 2am after the data pull in other flow. 
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 2 * * *"
      
name: deploy-shiny

jobs:
  # This workflow contains a single job called "scheduled-fetch-data"
  fetch-data-and-deploy-shiny:
    runs-on: macOS-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: configure pip caching
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python_requirements.txt
    - name: Fetch, update and commit COVID-Ireland data
      run: . /DATA/get-data.sh
    - name: Set up R
      uses: r-lib/actions/setup-r@master
    - name: install-R-packages
      run: |
        Rscript -e "install.packages(c('renv'), type  = 'binary')"
        Rscript -e "renv::restore()"
    - name: authorise-shiny
      run: |
        Rscript -e "rsconnect::setAccountInfo(name='iboboburo', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
        Rscript -e "rsconnect::deployApp(appName = 'coviddash')"
