on:
  # Trigger the workflow on pull request on master branch 
  # or can kick off manually if needs be.
  pull_request:
    branches:
      - master
  workflow_dispatch:
      
name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: install-packages
        run: |
         Rscript -e "install.packages(c('renv'), type  = 'binary')"
         Rscript -e "renv::restore()"
      - name: authorise-shiny
        run: |
         Rscript -e "rsconnect::setAccountInfo(name='iboboburo', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
         Rscript -e "rsconnect::deployApp(appName = 'coviddash')"
